const DADOS = {}

DADOS.TITLE = "Educacenso";
DADOS.SUBTITLE1 = "SigeEscola";
DADOS.SUBTITLE2 = "Sistema Integrado de Gestão Escolar";
DADOS.FOOTER1 = "SEDUC.CE.GOV.BR - © 2018 – GOVERNO DO ESTADO DO CEARÁ";
DADOS.FOOTER2 = "TODOS OS DIREITOS RESERVADOS";

export const CONSTANTS = DADOS;